### ISSUE TITLE
Random accidental code review

### ISSUE THREAD

**Issue by izik1** [lenscas/card_game#55]
https://github.com/lenscas/card_game/blob/fffcc204f29a8c9ef909c9d4fcd667249d2c34ec/src/battle/deck.rs#L61-L66

Could be better written (without an expect) as such:
```rust
self.casted.push(card.clone());
Ok(card)
```

**Comment by lenscas** [comment]
Thanks for the random code review.

And yes, your method is MUCH better. No idea why I didn't write it like this in the first place.
